### ISSUE TITLE
hudge bundle size

### ISSUE THREAD

**Issue by nicitaacom** [resendlabs/react-email#1340] opened 2024-03-04 16:16 UTC
### Describe the Bug

WTF?
![image](https://github.com/resend/react-email/assets/39565703/b0c97523-aa80-432d-bbc4-3c349839ce49)

![image](https://github.com/resend/react-email/assets/39565703/e48b160e-66e8-4754-a897-88ed4399e033)

<br/>

[With](https://pagespeed.web.dev/analysis/https-23-store-cl7bq5xo3-nicitaacom-vercel-app/0zfd9c4zo3?form_factor=mobile)

![image](https://github.com/resend/react-email/assets/39565703/f17e2d89-bae6-4fff-b950-297b86a44e86)

<br/>

[Without](https://pagespeed.web.dev/analysis/https-23-store-nvl5wi4l3-nicitaacom-vercel-app/rw5lhzyd64?form_factor=mobile)

![image](https://github.com/resend/react-email/assets/39565703/ebd4dcf0-0208-41ff-96bb-f558b73a2d2c)

### Which package is affected (leave empty if unsure)

@react-email/components

### Link to the code that reproduces this issue

https://github.com/nicitaacom/acc2-send-email-react-email-resend

### To Reproduce

1. Jsut use `renderAsync` function from
`import { renderAsync } from "@react-email/components"`

### Expected Behavior

I see hudge bundle size that reduce performance in google page speed

**Comment by gabrielmfern** [comment] 2024-03-04 16:17
Closing as a duplicate of #1329

**Closed as not planned by gabrielmfern** 2024-03-04 16:17 UTC
Labels: Type: Bug
