### ISSUE TITLE
Automatic Setup emails folders error

### ISSUE THREAD

**Issue by Facug03** [resendlabs/react-email#988] opened 2023-10-26 13:44 UTC
### Describe the Bug

When i run the project it installed me all the dependencies but the emails folder was not created and it gave me and error, i thought i have to move the emails folder inside but it didnt work, then i tried the manual setup and it created the folder automatically

### Which package is affected (leave empty if unsure)

react-email

### Link to the code that reproduces this issue

https://github.com/resendlabs/react-email

### To Reproduce

just follow the steps of the automatic setup

### Expected Behavior

i expected to run the project correctly

**Comment by gabrielmfern** [comment] 2023-11-04 11:48
Can you expand on what error you had when running the automatic setup? It probably is a problem with monorepos, if so it is a known issue and there is a PR underway that'll solve this and other problems.

**Comment by tommerty** [comment] 2023-11-09 13:31
Hi, facing the same error. The error I'm seeing is:

```
Unhandled Runtime Error
Error: ENOENT: no such file or directory, scandir 'C:\Users\thoma\Documents\GitHub\doras\email\react-email-starter\.react-email\emails'
```

If you then manually copy/paste the `emails` dir into `.react-email` while dev isn't running, when you run dev, it removes it. If you copy `emails` dir in while dev is running, the homepage compiles but you can see the following in the console:

```
Server Error
TypeError: Cannot read properties of null (reading '1')

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Source
src\app\preview\[slug]\page.tsx (36:75) @ Page

  34 |   encoding: 'utf-8',
  35 | });
> 36 | const importPath = exportTemplateFile.match(/import Mail from '(.+)';/)![1];
     |                                                                         ^
  37 | const originalFilePath = pathJoin(dirname(path), importPath);
  38 | 
  39 | const reactMarkup: string = await fs.readFile(originalFilePath, {
```

**Comment by tommerty** [comment] 2023-11-09 13:38
Seems this issue is a duplicate of https://github.com/resendlabs/react-email/issues/677.

Found a fix in there: https://github.com/resendlabs/react-email/issues/677#issuecomment-1568082975

**Comment by gabrielmfern** [comment] 2023-11-09 13:40
> Seems this issue is a duplicate of #677.
> 
> Found a fix in there: [#677 (comment)](https://github.com/resendlabs/react-email/issues/677#issuecomment-1568082975)

@tommerty Does the 1.9.5 also not work?

**Comment by tommerty** [comment] 2023-11-09 15:30
> [@tommerty](https://github.com/tommerty) Does the 1.9.5 also not work?

Can confirm `1.9.5` works, just updated. The `npx create-email@latest` downloaded `1.9.3`.

**Comment by gabrielmfern** [comment] 2023-11-11 07:37
Closing this as a duplicate of #677

**Closed by gabrielmfern** 2023-11-11 07:37 UTC
Labels: Type: Bug, Package: @react-email/react-email
