### ISSUE TITLE
'email export' hangs up on "Preparing files..."

### ISSUE THREAD

**Issue by coreybruyere** [resendlabs/react-email#944] opened 2023-09-28 18:55 UTC
### Describe the Bug

After installing and going through steps 1-3 in [Automatic Setup](https://react.email/docs/getting-started/automatic-setup), then installing [SendGrid SDK and packages ](https://react.email/docs/integrations/sendgrid), I get stuck on "Preparing files..." when trying to run `npm run export`.

### Link to the code that reproduces this issue

NA

### To Reproduce

- Go through automatic setup
- Install SendGrid SDK + packages
- Create index.tsx in `emails/`
- Add example template below with SendGrid API key to index.tsx
- Run `npm run export`

```

import { render } from "@react-email/render";
import sendgrid from "@sendgrid/mail";
import StripeWelcomeEmail from "./stripe-welcome";
import React from "react";

sendgrid.setApiKey(
  "[[YOUR API KEY]]"
);

const emailHtml = render(<StripeWelcomeEmail />);

const options = {
  from: "you@example.com",
  to: "user@gmail.com",
  subject: "hello world",
  html: emailHtml,
};

sendgrid.send(options);

```

### Expected Behavior

Export command should emit an error or export the email

### What's your node version? (if relevant)

v20.7.0

**Comment by Maclay74** [comment] 2023-09-29 14:54
Yea, it's broken.

I think it's related to the building stage via `esbuild`.
It can't be dynamically imported later.

**Comment by Maclay74** [comment] 2023-09-29 17:40
Okay, I resolved it for me. In my case I didn't import React (and didn't have it installed), therefore it didn't work for me. 
Although, probably I know how you can find out what's wrong with your code.

I created a new file and tried to follow the same pipeline, this way it shows errors. 
There must be a much easier way to enable errors, but... I found this. 

So for me it generated .js file, but not .html, so I imported my .js file and tried to call it. 

```ts
const render = require('@react-email/render').render

const test = async () => {
    const component = await import("./out/email.js")
    console.log(component.default.default({}))
}

test();
```

Good luck!

**Comment by spg** [comment] 2023-11-06 14:28
The fix for me as to `pnpm add react` at the root directory. Subsequent `pnpm email export` worked.

**Comment by gabrielmfern** [comment] 2023-11-11 08:23
Closing this as a duplicate of #803

**Closed by gabrielmfern** 2023-11-11 08:23 UTC
Labels: Type: Bug, Package: @react-email/react-email, Resolution: Duplicate
