### ISSUE TITLE
SyntaxError: Invalid regular expression: invalid group specifier name

### ISSUE THREAD

**Issue by JClackett** [resendlabs/react-email#549] opened 2023-03-16 12:57 UTC
Im using react-email in a Remix project and just rendering the emails in the route directory:

```tsx
// routes/emails/reset-password.tsx
import { Tailwind } from "@react-email/tailwind"


export default function Template(props: { link?: string }) {
  return (
    <Tailwind>
      <h1 className="text-6xl">Reset Password</h1>
      <p>Click below to reset your password</p>
      <a href={props.link}>Reset Password</a>
    </Tailwind>
  )
}

```
When using the Tailwind component I get a `SyntaxError: Invalid regular expression: invalid group specifier name` in the console.

**Comment by daun-io** [comment] 2023-03-31 01:35
This feels critical to us too.

**Comment by bukinoshita** [comment] 2023-04-05 19:49
Would mind sharing a reproduction repo or link?

**Comment by JClackett** [comment] 2023-04-05 21:02
here ya go, was having issues even getting it rendered now though! https://github.com/JClackett/remix-react-email

**Comment by derozn** [comment] 2023-06-16 17:23
+1 - Having the same issue on Safari.

**Comment by u3u** [comment] 2023-08-24 12:03
After research, I found that it is because Safari does not support Lookbehind regular expression matching: `(?<= )` (https://caniuse.com/js-regexp-lookbehind)
The underlying `tw-to-css` library also has the same problem: https://github.com/vinicoder/tw-to-css/issues/6 /cc @rretlaw @vinicoder 

https://github.com/vinicoder/tw-to-css/blob/6eb173e8006817d6a50ad00499274349a2d35c29/src/util/format-css.ts#L18

```js
const blockContentRegex = /(?<=\.)[^{]+\s*\{(?<content>[^{}]*(?:(?<=;)\s*\n\r?[^{}]*)*)\s*\}/gm;
```

Although we don't invoke the `merge` method, stupid Safari will throw an error as long as it is included in the code 😅, so we can simply remove `?<=` first.

<img width="531" alt="image" src="https://github.com/resendlabs/react-email/assets/20062482/af154de6-4505-4c86-91e0-767ee567400e">

https://github.com/resendlabs/react-email/blob/490e0356685c1a6406c89620687725d0b98ad53b/packages/tailwind/src/tailwind.tsx#L24-L28

Then replace `/(?<=.)[:#\!\-[\\\]\/\.%]+/g` with `/(?!^\.)[:#\!\-[\\\]\/\.%]+/g`

I'm not good at regular expressions, I only tested the basic case `.my-1{` -> `.my_1{`, if it causes other problems, you can remove the `cleanCss` method first.

https://github.com/resendlabs/react-email/blob/490e0356685c1a6406c89620687725d0b98ad53b/packages/tailwind/src/tailwind.tsx#L116-L118

Finally, we can use `pnpm patch @react-email/tailwind` & `pnpm patch tw-to-css` & [`pnpm patch-commit`](https://pnpm.io/cli/patch) or [patch-package](https://github.com/ds300/patch-package) to immediately fix it by modifying the regex.

**`@react-email__tailwind@0.0.8.patch`**

```diff
diff --git a/dist/index.js b/dist/index.js
index 98f14262c946c52495c0c45fb166628996d11e6e..c8f123085476f1e82f4811460bc2b8865bc62a5c 100644
--- a/dist/index.js
+++ b/dist/index.js
@@ -100,7 +100,7 @@ var Tailwind = ({ children, config }) => {
 Tailwind.displayName = "Tailwind";
 function cleanCss(css) {
   let newCss = css.replace(/\\/g, "").replace(/[.\!\#\w\d\\:\-\[\]\/\.%\(\))]+(?=\s*?{[^{]*?\})\s*?{/g, (m) => {
-    return m.replace(/(?<=.)[:#\!\-[\\\]\/\.%]+/g, "_");
+    return m.replace(/(?!^\.)[:#\!\-[\\\]\/\.%]+/g, "_");
   }).replace(/font-family(?<value>[^;\r\n]+)/g, (m, value) => {
     return `font-family${value.replace(/['"]+/g, "")}`;
   });
diff --git a/dist/index.mjs b/dist/index.mjs
index 00d5b2bc460d97567ddd5688d24e0a23e034b7b4..393faf0bee94779a29918bced3d3bc927734d4e8 100644
--- a/dist/index.mjs
+++ b/dist/index.mjs
@@ -68,7 +68,7 @@ var Tailwind = ({ children, config }) => {
 Tailwind.displayName = "Tailwind";
 function cleanCss(css) {
   let newCss = css.replace(/\\/g, "").replace(/[.\!\#\w\d\\:\-\[\]\/\.%\(\))]+(?=\s*?{[^{]*?\})\s*?{/g, (m) => {
-    return m.replace(/(?<=.)[:#\!\-[\\\]\/\.%]+/g, "_");
+    return m.replace(/(?!^\.)[:#\!\-[\\\]\/\.%]+/g, "_");
   }).replace(/font-family(?<value>[^;\r\n]+)/g, (m, value) => {
     return `font-family${value.replace(/['"]+/g, "")}`;
   });
```

**`tw-to-css@0.0.11.patch`**

Because the `tw-to-css/dist/*` file is compressed, the generated patch file is too long, so it will not be released. Search for `?<=` and delete it.

By the way, I want to tell @vinicoder that our published npm package does not need to be compressed. It will eventually be compressed by the user's build tool.

I don't know how many times I have worked overtime because of garbage Safari. Unfortunately, there are too many iOS users and all Apple platform browsers use Safari as their kernel. `Safari === IE6`, Apple you're great 👍

Finally, I just want to say again: **Fuck Safari! Safari must go die! 😅**

**Comment by u3u** [comment] 2023-08-26 15:17
I eventually returned to using the native `style` prop for styling because I found that using tw-to-css resulted in poor rendering performance and it had a large file size (~79kb). If you want to render email templates in client browsers, it's best to go back to the most primitive way, even though it's much more troublesome to write 😰. It is a good choice for pure server-side rendering, and when I first saw it, it impressed me!

<img width="942" alt="image" src="https://github.com/resendlabs/react-email/assets/20062482/86f1ab23-b057-4ffe-9021-cfd34c7c354c">

**Comment by vinicoder** [comment] 2023-08-31 14:34
Hey everyone!

I just wanted to apologize for my absence over the past few months. Juggling my role as a company leader and caring for my little ones has proven to be quite the challenge. However, I'll work on some updates and fixes in the upcoming weeks.

I created the' tw-to-css' package and have been maintaining it solo. Your help in improving it by reporting any bugs has been greatly appreciated. I know it's not perfect, but it was a challenging feat, and I'm confident we can work together to improve it.

Thank you all so much.

**Comment by eminx** [comment] 2023-10-19 01:10
Hey guys,

I'm struggling here exactly with this problem, due to Safari.

Can anyone help me implement an easy solution please?

The problem is that as soon as I import the components, Safari crashes...

```
import {
  Body,
  Button as EmButton,
  Column,
  Container,
  Head,
  Heading as EmHeading,
  Hr,
  Html,
  Img,
  Link as EmLink,
  Row,
  Section,
  Text as EmText,
} from '@react-email/components';
```

I'm using `@react-email/components@0.0.7`

@u3u @vinicoder thanks

**Comment by u3u** [comment] 2023-10-19 03:31
@eminx Does this not work for you? https://github.com/resendlabs/react-email/issues/549#issuecomment-1691548992

**Comment by eminx** [comment] 2023-10-19 09:44
@u3u I'm having hard time implementing it... I have to go to the dependencies within the `react-email` package and do all the changes..? I've been writing React/JS for over 8 years and I find this fix very hard to do honestly... Is it me? 😖

**Comment by u3u** [comment] 2023-10-19 09:59
@eminx Yes, you need to manually modify the source code. Executing the command `pnpm patch @react-email/tailwind` will create a temporary directory for this module, and you can freely modify the source code of this module in the temporary directory (search for key codes and make corresponding modifications). After completing the modifications, execute the command `pnpm patch-commit <temporary directory path>` to generate a patch file and automatically apply it to the modules in `node_modules`. The patch file should be committed to `git` tracking so that all collaborators can automatically apply the patched modifications when executing `pnpm i`.

**Comment by eminx** [comment] 2023-10-21 10:14
Thank you so much @u3u !

**Comment by gabrielmfern** [comment] 2023-11-10 06:44
a PR is coming to close this issue for you guys without a patch

**Closed** 2023-11-19 16:51 UTC
Labels: Type: Bug, Package: @react-email/tailwind

**Comment by eminx** [comment] 2023-12-06 13:48
> a PR is coming to close this issue for you guys without a patch

@gabrielmfern @u3u  I tried to update the package to the latest one, but the problem persists - the crash in Safari. Any idea how I can resolve the issue? Thanks!

**Comment by u3u** [comment] 2023-12-06 14:53
@eminx Due to your version upgrade, the previous version's patches will become invalid. You need to repeat the previous patch operation. The official has made improvements on this issue. You can try upgrading to [`@react-email/tailwind@0.0.13-canary.4`](https://www.npmjs.com/package/@react-email/tailwind?activeTab=versions) version, which should work without patches.

**Comment by eminx** [comment] 2023-12-06 16:34
@u3u Dear I can't do it still... I have not managed to make the fix you suggested at the comment #549 - was hoping the newest PRs would resolve the issue. But it didn't...

Now I tried to install the @react-email/tailwind package you suggested but it doesn't help either. 

Sorry I really need this fix. Would appreciate your help. Thanks!

**Comment by gabrielmfern** [comment] 2023-12-07 11:50
> @u3u Dear I can't do it still... I have not managed to make the fix you suggested at the comment #549 - was hoping the newest PRs would resolve the issue. But it didn't...
> 
> Now I tried to install the @react-email/tailwind package you suggested but it doesn't help either.
> 
> Sorry I really need this fix. Would appreciate your help. Thanks!

The latest version is published, you can try either updating the components if you are importing Tailwind from it, or updating the direct package if you import from (`@react-email/tailwind`)

**Comment by eminx** [comment] 2023-12-08 13:22
My is resolved installing and importing components individually, like:

`import {Html} from '@react-email/html'`

Thanks! @gabrielmfern @u3u !

**Comment by DiegoGonzalezCruz** [comment] 2024-04-05 02:54
Hello! I just came here to say this still is an issue and it was so difficult to find the bug. I am eliminating the Tailwind component from react-email.

**Comment by gabrielmfern** [comment] 2024-04-05 09:20
@DiegoGonzalezCruz We don't use the same look behind or look ahead expressions in the regexes, we even have an ESLint rule for this now. Could your issue be something else? Please consider opening an issue with a proper reproduction before stopping the use of the component.
