### ISSUE TITLE
Unexpected token '<' when export email

### ISSUE THREAD

**Issue by hiddenest** [resendlabs/react-email#952] opened 2023-10-01 12:04 UTC
### Describe the Bug

In development environment, the rendering works properly like this:
<img width="962" alt="스크린샷 2023-10-01 오후 8 57 33" src="https://github.com/resendlabs/react-email/assets/8682478/ebaadfc0-4bb9-4e0a-b496-766a60fb2269">

However, it throws error once you try to export:
```
> email export --pretty

✔ Preparing files...

⠋ rendering reset-password-en.jsnode:internal/validators:95
      throw new ERR_INVALID_ARG_TYPE(name, 'number', value);
      ^

TypeError [ERR_INVALID_ARG_TYPE]: The "code" argument must be of type number. Received an instance of SyntaxError
    at process.set [as exitCode] (node:internal/bootstrap/node:123:9)
    at Object.exit (node:internal/process/per_thread:188:24)
    at process.<anonymous> (/Users/hiddenest/Documents/me/react-email-module-import-error/node_modules/.pnpm/react-email@1.9.5/node_modules/react-email/dist/source/utils/start-server-command.js:43:27)
    at process.emit (node:events:514:28)
    at process.processEmit [as emit] (/Users/hiddenest/Documents/me/react-email-module-import-error/node_modules/.pnpm/signal-exit@3.0.7/node_modules/signal-exit/index.js:199:34)
    at process._fatalException (node:internal/process/execution:159:25)
    at processPromiseRejections (node:internal/process/promises:289:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:32) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

After adding `console.log()` to `start-server-command.js` with the result of `code` variable,
I found that the react-email couldn't understand react component.

```
⠋ rendering reset-password-en.js/Users/hiddenest/Documents/me/react-email-module-import-error/out/reset-password-en.js:39449
var Head = ({ language, title, children }) => <dist_exports.Head>
                                              ^

SyntaxError: Unexpected token '<'
```

### Which package is affected (leave empty if unsure)

react-email

### Link to the code that reproduces this issue

https://github.com/hiddenest/react-email-module-import-error

### To Reproduce

1. Install packages (`pnpm install --frozen-lockfile`)
2. Run export command (`pnpm export`)

### Expected Behavior

email should be exported

### What's your node version? (if relevant)

v20.7.0

**Comment by Mykhol** [comment] 2023-10-02 00:44
I also had this error, I've been having issues within our repository at the moment with different supported versions of node. Downgrading to `v18.17.1` resolved this issue for me. I was using `v20.x` previously.

**Comment by hiddenest** [comment] 2023-10-02 03:59
Interesting. When I downgraded to 18.18.0 and tested it, I don't get any errors, but the process seems to kill and the export doesn't happen.

To solve this problem, I wrote a script to generate HTML manually as shown below:

```ts
import path from 'path';
import fs from 'fs/promises';

import { renderAsync } from '@react-email/components';

const ROOT = path.resolve(process.cwd(), './emails');
const DIST = path.resolve(process.cwd(), './out');

const exportEmail = async () => {
  const lists = await fs
    .readdir(ROOT)
    .then((files) => files.filter((file) => file.endsWith('.tsx')));

  await createOutDir();

  await Promise.all(
    lists.map(async (list) => {
      const url = path.resolve(ROOT, list);
      await renderHTML(url);
    }),
  );
};

const createOutDir = async () => {
  try {
    const stats = await fs.stat(DIST);
    if (stats.isDirectory()) {
      return;
    }

    await fs.mkdir(DIST);
  } catch {
    await fs.mkdir(DIST);
  }
};

const renderHTML = async (url: string) => {
  const module = await import(url);
  const filename = path.basename(url, '.tsx');

  try {
    const html = await renderAsync(module.default({}), { pretty: true });
    await fs.writeFile(path.resolve(DIST, `${filename}.html`), html);

    console.log(`✅ Exported ${filename}.html`);
  } catch (error) {
    console.log('-----------------------------------------------------');
    console.log(`❌ Failed to export ${filename}.html`);
    console.error(error);
    console.log('-----------------------------------------------------');
  }
};

exportEmail();

export {};
```

**Comment by zeekrey** [comment] 2023-10-10 09:13
Hey @hiddenest, I think your script looks great, so I decided to give it a try. Unfortunately, `renderAsync` is exported by `@react-email/render`. When I changed the import statement, I encountered the error `SyntaxError: The requested module '@react-email/components' does not provide an export named 'Body'`. 😞

**Comment by gabrielmfern** [comment] 2023-11-10 09:50
Looking into this now, This is a bug with the way the `export` command works. The problem is that we bundle the code temporarily in a .js file to be able to import it without jsx and problems with paths, but what happens is that since it is building typescript, it is building based on the jsx property on the tsconfig, thus keeping the jsx that the CLI can't parse.

A workaround for now would then be setting the jsx to be `react-jsx` but this is certainly a bug and I'm going to look into fixing this

**Comment by gabrielmfern** [comment] 2023-11-11 08:48
Going to close this as a duplicate of  #952.

**Closed by gabrielmfern** 2023-11-11 08:48 UTC
Labels: Type: Bug, Package: @react-email/react-email, Resolution: Duplicate

**Comment by phgn0** [comment] 2024-11-05 08:29
FYI, adding `"jsx": "react-jsx"` to my Node.js `tsconfig.json` fixed this issue for me.
